### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by mcollina** [fastify/releasify#10]
I think we can release this. I’m eager to start using it, it would speed up my dev workflow significantly already.

**Comment by Eomm** [comment]
I wrote the email to get the package name but I haven't a reply yet.
The policy says we should still wait 2 weeks

So:
+ release with a new or fake name or another npm-registry?
+ v `0.0.1` or `1.0.0-RC1` ?

**Comment by mcollina** [comment]
Let's go with `0.1.0` and `@fastify/releasify` for now.

**Comment by Eomm** [comment]
Published [v0.1.0](https://www.npmjs.com/package/@fastify/releasify) 👍

**Comment by mcollina** [comment]
Can you tag the realease using the tool's draft? :D

**Comment by Eomm** [comment]
Sure, I was forgetting it 😅
