### ISSUE TITLE
releasify says that it couldn't create the github release but it did

### ISSUE THREAD

**Issue by simoneb** [fastify/releasify#122]
## 🐛 Bug Report

As per subject

## To Reproduce

`releasify publish`

generates error:

```
   Error: Something went wrong creating the relase on GitHub.
    The 'npm publish' and 'git push' has been done!
    Consider creating a release on GitHub by yourself with this message:
```

but the github release was created

## Expected behavior

No error message printed

## Your Environment

- *node version*: 14
- *os*: Windows

**Comment by Eomm** [comment]
I think this is caused by the warnings in the `stderr` due the old dependencies.

This module is not up-to-date because I'm blocked here https://github.com/fastify/releasify/issues/42
If I could automate the OTP a refresh of this module would worth the effort

There is this PR that is starving 😢 
https://github.com/mmarchini-oss/npm-otp-publish/pull/67

**Comment by mcollina** [comment]
Maybe let's fork/embed that code?

**Comment by Eomm** [comment]
I don't have time in the near future to work on it.

I saw that @simoneb and @Fdawgs are very proficient with automation, so if you would like to work on this task I can help you understand where I stopped

**Comment by Eomm** [comment]
@simoneb could you share more info? Was the repository private?

Running `releasify publish -n -m -s major --npm-opt 123123` did not show up the error message.

![image](https://user-images.githubusercontent.com/11404065/133256983-5fa876b4-3deb-4af1-a8ac-5bbafccaafcb.png)

**Comment by simoneb** [comment]
Yeah it wasn't systematic, I believe it was happening in repos which contained a package-lock.json file, even though I'm not 100% sure about it. It was working just fine in many other cases instead, and I'm not sure I've identified the actual issue.
