### ISSUE TITLE
draft should require a semver level

### ISSUE THREAD

**Issue by mcollina** [fastify/releasify#14]
Generating a release without bumping the version number is not a great idea.

**Comment by Eomm** [comment]
The original idea was that the semver must be understood by the script using the labels of PR and also to manage the first release of a package.

Now this is not well structured (semver is/will be mandatory for the publish command) so for sure a harmonization PR will be done to polish the possible use cases 👍

**Comment by Eomm** [comment]
Done

```
$ releasify draft
ERROR: .semver should be equal to one of the allowed values
    Error: .semver should be equal to one of the allowed values
```
