### ISSUE TITLE
Ping command doesn't returned success

### ISSUE THREAD

**Issue by mcollina** [fastify/releasify#18]
When I run `releasify publish -s minor -k TOKEN` , I get:

```
ERROR: Ping command doesn't returned success
    Error: Ping command doesn't returned success
        at Object.ping (/Users/matteo/.nvm/versions/node/v10.15.2/lib/node_modules/releasify/lib/npm.js:32:15)
```

Apart from the grammar error (correct `Ping command was not successful`) - I don't see what I'm doing wrong.

**Comment by Eomm** [comment]
this is the check done:

https://github.com/fastify/releasify/blob/3f488f5c8714de6624d16bf45e1933b69bc4a3ed/lib/commands/publish.js#L94

Could you try to run directly `npm ping` in your console? It should print out `Ping success: {}`

**Comment by mcollina** [comment]
```
$ npm ping
npm notice PING https://registry.npmjs.org/
npm notice PONG 1.177ms
```

**Comment by Eomm** [comment]
Ok, this check must be removed so

https://github.com/fastify/releasify/blob/3f488f5c8714de6624d16bf45e1933b69bc4a3ed/lib/npm.js#L31

**Comment by mcollina** [comment]
I think checking if the return is code is 0 would be enough
