### ISSUE TITLE
Unstable open-editor

### ISSUE THREAD

**Issue by Eomm** [fastify/releasify#21]
We notice that opening the editor in "wait" mode is not stable in:
- windows with vscode, notepad, notepad++

The issue happens when the editor is already opened, when it is closed it works (with tons of absolute path configured in order to run in windows).

The module used is [open](https://www.npmjs.com/package/open), preferred to `open-editor` because the last one doesn't have the `wait` option.

A snippet to try locally:
```
const { editMessage } = require('./lib/editor')

async function run () {
  const e = await editMessage('hello', 'hello.md')
  console.log(e)
}

run()
```

**Comment by mcollina** [comment]
I found out the problem. `open` is going to open XCode for this, which takes forever. 
Using https://www.npmjs.com/package/open-editor would solve this.

**Comment by Eomm** [comment]
Clear, but the doc says:

> It does not wait for the editor to start or quit.

and I need a trigger to understand when the editing is complete to put the content in the github release.

I will check out if I can merge these two libs in one

**Comment by Eomm** [comment]
I checked deeply and I need to solve two problems:

1. in windows there is some fixed to do ( https://github.com/sindresorhus/open-editor/pull/9 )
1. find the `--wait` args for the editors used by the 

Anyway, PR is coming
