### ISSUE TITLE
Use Github Auto-Generated Release Notes

### ISSUE THREAD

**Issue by climba03003** [fastify/releasify#255]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Instead of self modify one or using the old format.
Github provide it's well-formatted and pretty release notes.

We can enable to use the release notes with a single option `generate_release_notes`.
https://docs.github.com/en/rest/releases/releases#create-a-release

The idea is pretty simple. If the user do not pass `--gh-release-edit | -e` for a custom one.
We use the auto-generate one.

**Comment by Eomm** [comment]
Totally agree
