### ISSUE TITLE
How to manage the authentication

### ISSUE THREAD

**Issue by Eomm** [fastify/releasify#3]
Check how to manage the authentication process. The problems to face are 3:

- [ ] github auth to interact with repo
- [ ] npm for the publishing of the module
- [ ] a little thought to CI/CD - we don't want to close this door too soon

I used already the Github API but I used a token:

https://github.com/Eomm/next-node-bot/blob/b5dc70255d9bf5d97fac780224e9788a0b9fddf3/index.js#L13

But I know it is only for private usage.. for what I know now I should go deeper

**Comment by mcollina** [comment]
The tool should work with _zero_ setup on the repo side. We have 30+ repositories in this repo, and we should really avoid to configure them all.

**Comment by Eomm** [comment]
Yes, sure!!

I was thinking that there are 3 auth we could use:
+ git client, using the `spawn`.. so we don't' have to manage anything
+ npm client, using the `spawn`.. so we don't' have to manage anything
+ Github API, we need to deal with it because there isn't a "build a release" command in the cli, but only a tag

In this way, it should be quite simple to do, but for sure we can't think on CI/CD because nobody installs `git client` on the CI server 😅

**Comment by mcollina** [comment]
You don’t need to auth the git client, nor npm. You just need to auth github with a personal access token.

**Comment by mcollina** [comment]
(auth for git and npm isngoing to be done by the user separately)

**Comment by Eomm** [comment]
Does someone know if there is some "dev" environment to try the GitHub Rest API?

I have googled a bit but I don't find anything more than the test-env for GH APP

**Comment by mcollina** [comment]
Yes there is! Create a personal repo!

**Comment by Eomm** [comment]
Solved
