### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by Eomm** [fastify/releasify#6]
The name `releasify` it is [used](https://www.npmjs.com/package/releasify)

Could we ask if the user is so kind to free the name or should we squeeze our fantasy? 😁

**Comment by mcollina** [comment]
Go for it! 

Read https://docs.npmjs.com/misc/disputes.html and follow the process.

**Comment by Eomm** [comment]
> Hi chimon2000,
> 
> As we've not heard back, we've moved forward with the other user, eomm's request to utilize the releasify package name. If you'd like to learn more about our names dispute policies, you can here: https://www.npmjs.com/policies/disputes
> 
> eomm: It’s all yours now, but you won’t be able to re-use any version numbers used by the previous author. In fact, I'd suggest publishing your first update as a major release, i.e., v1.0.0. Please publish an update to the package as soon as possible with your code.

Releasing v1.0.0 in few hours

I have to check how give permission to the fastify org
