### ISSUE TITLE
Command draft

### ISSUE THREAD

**Issue by Eomm** [fastify/releasify#7]
Details #1

**Comment by Eomm** [comment]
Find these main steps

#### take last tag released 
`git tag --format='%(objectname) %(refname:strip=2)' --sort=-version:refname -l v1* | head -n1`
[NOTE]: need a pattern input (example: `v1*`)

#### find the diff
```
git log --pretty=oneline HEAD...`git tag --format='%(objectname)' --sort=-version:refname -l v1* | head -n1`
```

#### extract the PR IDs
`/(#\d{1,5})/gm`

#### ask the labels to GITHUB foreach PR
https://developer.github.com/v3/pulls/#get-a-single-pull-request

#### analyze the labels to choose from [major, minor, patch]
print out the result
[NOTE for PUBLISH command] if major => block it (unless there is a boolean option)

#### compose the GITHUB Release string message
print out the result
[NOTE for PUBLISH command] https://developer.github.com/v3/repos/releases/

**Comment by mcollina** [comment]
Awesome work!
